DROP DATABASE IF EXISTS ACADEMICO_SENA;
CREATE DATABASE ACADEMICO_SENA;
USE ACADEMICO_SENA;

CREATE TABLE APRENDIZ(
    ID_APR INT AUTO_INCREMENT PRIMARY KEY,
    NOM_APR VARCHAR (20),
    APE_APR VARCHAR (20),
    TDO_APR CHAR(2),
    NDO_APR VARCHAR (15),
    TEL_APR CHAR(10),
    FOT_APR VARCHAR(50)
);



