DROP DATABASE IF EXISTS ACADEMICO_SENA;
CREATE DATABASE ACADEMICO_SENA;
USE ACADEMICO_SENA;

CREATE TABLE APRENDIZ(
    ID_APR INT AUTO_INCREMENT PRIMARY KEY,
    NOM_APR VARCHAR (20),
    APE_APR VARCHAR (20),
    TDO_APR CHAR(2),
    NDO_APR VARCHAR (15),
    TEL_APR CHAR(10),
    FOT_APR VARCHAR(50)
);

CREATE TABLE INSTRUCTOR(
    ID_INS INT AUTO_INCREMENT PRIMARY KEY,
    NOM_INS VARCHAR (20),
    APE_INS VARCHAR (20),
    TDO_INS CHAR(2),
    NDO_INS VARCHAR (15),
    TEL_INS CHAR(10),
    FOT_INS VARCHAR(50)
);

CREATE TABLE COMPETENCIA(
    ID_COM INT AUTO_INCREMENT PRIMARY KEY,
    NOM_COM VARCHAR (20),
    CONT_COM VARCHAR (15),
    RESU_COM CHAR(10),
    PROG_COM VARCHAR(20)
);

CREATE TABLE FICHA(
    ID_F INT AUTO_INCREMENT PRIMARY KEY,
    NUM_F CHAR (10),
    NUM_APR_F CHAR (10)
    PROG_F VARCHAR(20)
);
